### ISSUE TITLE
Question: levels on functional profiling?

### ISSUE THREAD

**Issue by tanaes** [knights-lab/SHOGUN#17]
@bhillmann @GabeAl What exactly is the 'levels' specifying for predictive functional profiling? Often I get very sparse output tables for higher levels, e.g. genus.

**Comment by bhillmann** [comment]
The KO table is summarized at the lowest level. This is because the mapping from reference ids (eg. NC_0001.1) to Kegg IDs (eg. KO0001) are done using Prokka. In the rep82 database, every entry in the FASTA is a full genome from RefSeq version 82 with a strain level annotation. Each of the full reference genomes that are prokaryotes are run through [PROKKA ](https://github.com/tseemann/prokka)to identify which KEGG ids are within that genome. Therefore we have a mapping from taxonomy at the strain level to ko's as shown [here](https://github.com/knights-lab/SHOGUN/blob/master/shogun/tests/data/function/ko-strain2ko.txt). If your taxatable is not summarized at the strain level, then we must convert this ko-strain2ko to a higher level. This is done now by collapsing the one-to-many (a genus has potentially many strains in it) by a 80% plurarlity vote (each KEGG ID for a genus must belong in 80% of the strains).

**Comment by tanaes** [comment]
So just to check my intuition then, if I have a taxonomy profile that has the following lines:

```
k__Bacteria;p__Actinobacteria;c__Actinobacteria;o__Actinomycetales;f__Actinomycetaceae;g__Actinomyces;s__Actinomyces_odontolyticus;t__Actinomyces_odontolyticus_ATCC_17982      14
k__Bacteria;p__Actinobacteria;c__Actinobacteria;o__Actinomycetales;f__Actinomycetaceae;g__Actinomyces;s__Actinomyces_oris       8
k__Bacteria;p__Actinobacteria;c__Actinobacteria;o__Actinomycetales;f__Actinomycetaceae;g__Actinomyces      1
```

the resulting 'strain' level functional profile will have *only* hits derived from the first line, the 'species' level functional profile will have *only* hits derived from the second line, and the 'genus' level *only* hits from the third line?
